def main():
    #Define counter variables that represent each base

    num_a = 0
    num_c = 0
    num_g = 0
    num_t = 0

    #Establish a variable for the DNA string and an empty list variable
    s1 = "CGAATATACCACGCCGTAAAGATGTTGGCTGAACGGCTCACCATCTTTTAATATACTGAAGAGGGCATTTTCCAAATACCCGGAAGTCCTGACAGTGCGTCCGATCGTCGGATGTAGCGAGGGTGGAGACGGTCGCTCAGAATGGTATTTGCTTTGATGGATCTGTACACAATTTGATATTAAGAAACTGGTGCTGAGCTAATTGAACCAGACTTAACTGAAGCACTATAGTAGCCGAGGGGCGTAGAGTGTAACCTCCACTGACGATTTGACCAATGTATAACCGGTAGCCATATTGCTATATAACGGCGGGCCAAGGTCTAAAATGTAGTAAGTTTACCCTAGTCTAACCTTGACCGCCCCCGAAACAACACCATGGCCAATTGGAGTCTAGTAAGTTATAATTGGGGCTGATTGCGCCACTGTGGAGGTACAACTAATCAATTATCCCTCGATGCACCGCTATGTACGAAGCCTCCTCAATGTGGATAAGCTGCTATACCCGAGAGGGTGGTCTAGGTAGCTGCGTGGTCTTCCACCGTTGCATGAGGGGTTGTCGGACCTATATACCCCCTCCCGTAACAAGCTACTGCAGGGATACACTTTTGGACCCTTTAATACTAGAGCGCGCATGCCTTGCATATGTCCCAAGCCGGTGGACGAAATGACCAAAAACACGGGAAACCGTGTTCGTTAGCGCTAAATCCACCCCGGGTGGCCTAGGTATCAATATACTGCGAAAGCCACACGACTGGAATCAAGCTCCCGTTCAGGGAAATCTCCAAATAATTCGAGCTAGTGACGTGCCCTGCATCATAATAACCAACGATACGCTAGGCAGTTTGAATTTTTCCGATGGGGGGCACATTCGGTCCGTTAGTGACAATTTACTCTCTCAACATCAATGGACCGAACACAACCCCCTTCCGGATCGACGCGACCAGAATGTTCCACCTCTTCCAGGCTCAT"
    s2 = []

    #Establish a loop that turns the string into a list that can be properly counted
    for i in s1:
        s2.append(i)
        if i == "A" or i == "a":
            num_a += 1
        elif i == "C" or i == "c":
            num_c += 1
        elif i == "G" or i == "g":
            num_g += 1
        elif i == "T" or i == "t":
            num_t += 1
        else:
            continue
    
    #Print desired output
    print s2
    print str(num_a) + " " + str(num_c) + " " + str(num_g) + " " + str(num_t)




main()